version: "3"
services:
  lab-app-api:
    image: lab-app-api
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"

  lab-app-proxy:
    image: lab-app-proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3001:3001"

  lab-app-database:
    image: mariadb:10.3.9
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
    - db_volume:/var/lib/mysql
volumes:
  db_volume:
    external: true
